#!/usr/bin/env bash

#App firewall script by Gaetan. Add discord: 'Gaetan#7171' for helping.
#Version: 1.0

#------------------------------------------------------------------------------------------
#Variable

IPTABLES="sudo iptables" # The location of iptables
MINECRAFT_PORT="25565" # The port of your minecraft server

burstconns=20 # Limit new connections per second. This is highly useful when
              # somebody starts an attack because it basically makes his attack
              # literally have no visual effect.
              # 
              # Don't rely solely on this as this doesn't really fix the issue,
              # just get rid of suspicious IP's.
#------------------------------------------------------------------------------------------


echo "Rules loading..."

# 3 way handshake
$IPTABLES -t mangle -A PREROUTING -p tcp -m conntrack --ctstate ESTABLISHED -j ACCEPT
$IPTABLES -t mangle -A PREROUTING -p tcp ! --tcp-flags ALL SYN -j DROP
echo " -> Step 3W Handshake successfully."

$IPTABLES -t mangle -A PREROUTING -p tcp -m tcp --syn --tcp-option 8 --dport $MINECRAFT_PORT -m limit --limit 3/s -j ACCEPT
$IPTABLES -t mangle -A PREROUTING -p tcp -m tcp --syn --tcp-option 8 --dport $MINECRAFT_PORT -j DROP
echo " -> Step limit Linux TCP."

#------------------------------------------------------------------------------------------
#Bot Manager

# Step 1. Create & Flush Table
$IPTABLES -N BotManager
$IPTABLES -F BotManager

# Step 2. Check for the max connection amount to mitigate the attack.

$IPTABLES -A BotManager -p tcp --dport $MINECRAFT_PORT --syn -m limit --limit $burstconns/s -j ACCEPT
$IPTABLES -A BotManager -p tcp --dport $MINECRAFT_PORT --syn -j DROP

# Add BotManager to iptables and remove it just in case it is already there.
$IPTABLES -D INPUT -p tcp -j BotManager
$IPTABLES -A INPUT -p tcp -j BotManager

echo " -> Step Bot-Manager."
#------------------------------------------------------------------------------------------

echo "Rules successfully applied !"
